# Commands to start on workspace startup
tasks:
  - name: Commands Terminal
    init: echo "Use this terminal for any development related task"
  - name: Application Terminal
    init: go install github.com/cosmtrek/air@latest
    command: make run
    openMode: split-right

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview

# VS Code config
vscode:
  extensions:
    golang.go
    tal7aouy.icons
  