---
# Commands to start on workspace startup
tasks:
  - name: Commands Terminal
    before: 
      bash setup-gcp.sh &&
      gp open main.go &&
      source /home/gitpod/Apps/gcp/google-cloud-sdk/path.bash.inc &&
      source /home/gitpod/Apps/gcp/google-cloud-sdk/completion.bash.inc &&
      clear
    init: echo "Use this terminal for any development related task"
  - name: Application Terminal
    init: bash setup.sh
    command: clear && make run
    openMode: split-right

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview

# VS Code config
vscode:
  extensions:
    - golang.go
    - vscode-icons-team.vscode-icons
    - rangav.vscode-thunder-client
    - ms-vscode.makefile-tools
    - eamodio.gitlens
    - wayou.vscode-todo-highlight
